import os,sys,time

os.system('clear')
time.sleep(1)
print('')
print('\033[1;92mThis Tools Server off....');time.sleep(1)
print('\033[1;92mThis Tools Server off....');time.sleep(1)
print('')
print('\033[1;93mWaiting For Update....');time.sleep(1)
print('\033[1;93mWaiting For Update....');time.sleep(1)
print('')
print('\033[1;92mContact admin for tool information...');time.sleep(0.1)
os.system('xdg-open https://www.facebook.com/shifat.ff.buy.sell?mibextid=ZbWKwL')
print('')
exit()
